package com.darkorbit.objects;

public class Settings {
	/**
	 * Player settings
	 */

	public String SET, MINIMAP_SCALE, DISPLAY_PLAYER_NAMES, DISPLAY_CHAT, PLAY_MUSIC, PLAY_SFX,
				BAR_STATUS, WINDOW_SETTINGS, AUTO_REFINEMENT, QUICKSLOT_STOP_ATTACK, DOUBLECLICK_ATTACK, AUTO_START,
				DISPLAY_NOTIFICATIONS, SHOW_DRONES, DISPLAY_WINDOW_BACKGROUND, ALWAYS_DRAGGABLE_WINDOWS,
				PRELOAD_USER_SHIPS, QUALITY_PRESETTING, QUALITY_CUSTOMIZED, QUALITY_BACKGROUND,
				QUALITY_POIZONE, QUALITY_SHIP, QUALITY_ENGINE, QUALITY_COLLECTABLE, QUALITY_ATTACK,
				QUALITY_EFFECT, QUALITY_EXPLOSION, QUICKBAR_SLOT, SLOTMENU_POSITION, MAINMENU_POSITION, SLOTMENU_ORDER;
	
	/**
	 * Constructor
	 */
	public Settings(String SET, String MINIMAP_SCALE,
			String DISPLAY_PLAYER_NAMES, String DISPLAY_CHAT, String PLAY_MUSIC, String PLAY_SFX,
			String BAR_STATUS, String WINDOW_SETTINGS, String AUTO_REFINEMENT,
			String QUICKSLOT_STOP_ATTACK, String DOUBLECLICK_ATTACK, String AUTO_START,
			String DISPLAY_NOTIFICATIONS, String SHOW_DRONES, String DISPLAY_WINDOW_BACKGROUND,
			String ALWAYS_DRAGGABLE_WINDOWS, String PRELOAD_USER_SHIPS, String QUALITY_PRESETTING,
			String QUALITY_CUSTOMIZED, String QUALITY_BACKGROUND, String QUALITY_POIZONE,
			String QUALITY_SHIP, String QUALITY_ENGINE, String QUALITY_COLLECTABLE,
			String QUALITY_ATTACK, String QUALITY_EFFECT, String QUALITY_EXPLOSION,
			String QUICKBAR_SLOT, String SLOTMENU_POSITION, String SLOTMENU_ORDER, String MAINMENU_POSITION) {
		
		this.SET = SET;
		this.MINIMAP_SCALE = MINIMAP_SCALE;
		this.DISPLAY_PLAYER_NAMES = DISPLAY_PLAYER_NAMES;
		this.DISPLAY_CHAT = DISPLAY_CHAT;
		this.PLAY_MUSIC = PLAY_MUSIC;
		this.PLAY_SFX = PLAY_SFX;
		this.BAR_STATUS = BAR_STATUS;
		this.WINDOW_SETTINGS = WINDOW_SETTINGS; 
		this.AUTO_REFINEMENT = AUTO_REFINEMENT;
		this.QUICKSLOT_STOP_ATTACK = QUICKSLOT_STOP_ATTACK;
		this.DOUBLECLICK_ATTACK = DOUBLECLICK_ATTACK;
		this.AUTO_START = AUTO_START;
		this.DISPLAY_NOTIFICATIONS = DISPLAY_NOTIFICATIONS;
		this.SHOW_DRONES = SHOW_DRONES;
		this.DISPLAY_WINDOW_BACKGROUND = DISPLAY_WINDOW_BACKGROUND;
		this.ALWAYS_DRAGGABLE_WINDOWS = ALWAYS_DRAGGABLE_WINDOWS;
		this.PRELOAD_USER_SHIPS = PRELOAD_USER_SHIPS;
		this.QUALITY_PRESETTING = QUALITY_PRESETTING;
		this.QUALITY_CUSTOMIZED = QUALITY_CUSTOMIZED;
		this.QUALITY_BACKGROUND = QUALITY_BACKGROUND;
		this.QUALITY_POIZONE = QUALITY_POIZONE;
		this.QUALITY_SHIP = QUALITY_SHIP;
		this.QUALITY_ENGINE = QUALITY_ENGINE;
		this.QUALITY_COLLECTABLE = QUALITY_COLLECTABLE;
		this.QUALITY_ATTACK = QUALITY_ATTACK;
		this.QUALITY_EFFECT = QUALITY_EFFECT;
		this.QUALITY_EXPLOSION = QUALITY_EXPLOSION;
		this.QUICKBAR_SLOT = QUICKBAR_SLOT;
		this.SLOTMENU_POSITION = SLOTMENU_POSITION;
		this.MAINMENU_POSITION = MAINMENU_POSITION;
		this.SLOTMENU_ORDER = SLOTMENU_ORDER;
	}	
}
